In [1]:
import numpy as np
from sklearn import datasets

In [2]:
iris=datasets.load_iris()

In [3]:
X=iris.data
y=iris.target

In [4]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(iris.data,iris.target,test_size=0.2,random_state=233)

In [5]:
X_test.shape

(30, 4)

#### scikit-learn中的StandardScaler

In [6]:
from sklearn.preprocessing import StandardScaler

In [7]:
standardScaler=StandardScaler()

In [8]:
standardScaler.fit(X_train)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [9]:
standardScaler.mean_

array([5.86916667, 3.065     , 3.75916667, 1.19083333])

In [10]:
standardScaler.scale_

array([0.8416052 , 0.45417508, 1.78789895, 0.76267029])

In [11]:
X_train=standardScaler.transform(X_train)

In [12]:
X_test_standard=standardScaler.transform(X_test)

In [13]:
X_test_standard

array([[-0.79510758, -0.80365484,  0.0787703 ,  0.27425569],
       [ 1.10602137,  0.2972422 ,  1.19740175,  1.45432001],
       [ 0.27427746, -0.14311662,  0.47029131,  0.27425569],
       [ 1.46248305, -0.14311662,  1.19740175,  1.1920835 ],
       [-1.15156925,  0.07706279, -1.26358745, -1.29916341],
       [-1.15156925, -1.46419307, -0.25681914, -0.25021734],
       [ 0.27427746, -0.58347543,  0.52622288,  0.01201917],
       [-0.55746646,  1.83849807, -1.37545059, -1.03692689],
       [ 0.03663634, -0.14311662,  0.24656502,  0.40537395],
       [-0.31982534, -0.14311662,  0.19063344,  0.14313743],
       [ 0.1554569 , -0.36329603,  0.41435974,  0.40537395],
       [ 1.22484193,  0.07706279,  0.63808603,  0.40537395],
       [ 0.1554569 , -1.90455189,  0.6940176 ,  0.40537395],
       [-0.31982534, -0.14311662,  0.41435974,  0.40537395],
       [-0.91392813,  0.51742161, -1.1517243 , -0.90580863],
       [-1.50803093,  0.07706279, -1.26358745, -1.29916341],
       [-1.50803093,  0.

In [14]:
X_train

array([[-1.27038981, -0.14311662, -1.31951902, -1.16804515],
       [ 0.51191858,  0.51742161,  0.52622288,  0.53649221],
       [ 0.27427746, -0.58347543,  0.13470187,  0.14313743],
       [-1.03274869, -2.34491071, -0.14495599, -0.25021734],
       [-0.31982534, -0.80365484,  0.24656502,  0.14313743],
       [-0.55746646,  1.39813925, -1.26358745, -1.29916341],
       [ 0.98720081, -1.24401366,  1.14147018,  0.79872872],
       [-1.03274869, -1.68437248, -0.25681914, -0.25021734],
       [ 1.70012417, -0.36329603,  1.42112805,  0.79872872],
       [ 2.05658585, -0.14311662,  1.58892276,  1.1920835 ],
       [ 0.51191858, -0.80365484,  0.63808603,  0.79872872],
       [-1.03274869,  0.51742161, -1.31951902, -1.29916341],
       [-0.08218422, -0.80365484,  0.0787703 ,  0.01201917],
       [ 2.1754064 , -1.02383425,  1.75671748,  1.45432001],
       [-1.15156925,  0.07706279, -1.26358745, -1.43028167],
       [ 0.27427746, -0.36329603,  0.52622288,  0.27425569],
       [-0.55746646,  0.

#### 开始使用KNN预测

In [15]:
from sklearn.neighbors import KNeighborsClassifier

In [16]:
knn_clf=KNeighborsClassifier(n_neighbors=3)

In [17]:
knn_clf.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=3, p=2,
           weights='uniform')

In [18]:
knn_clf.score(X_test_standard,y_test)

0.9666666666666667