# Numpy

#### 1 功能：

- ndarray，一个具有矢量算术运算和复杂广播能力的快速且节省空间的多维数组；
- 用于对整组数组数据进行快速运算的标准数学函数（无需编写循环）；
- 用于读写磁盘数据的工具以及用于操作内存映射文件的工具；
- 线性代数、随机数生成以及傅里叶变换功能；

 在数据分析应用方面，功能是：
  - 用于数据整理和清理、子集构造和过滤、转换等快速的矢量化数据运算；
  - 常用的数组算法，如排序、唯一化、集合运算等；
  - 描述统计和数据聚合/摘要运算；
  - 用于异构数据集的合并/连接运算的数据对齐和关系型运算；
  - 将条件逻辑表述为数组表达式；
  - 数据的分组运算（聚合、转换、函数应用等）；

In [7]:
import numpy as np

In [8]:
my_arr=np.arange(1000000)

In [37]:
my_arr

array([     0,      1,      2, ..., 999997, 999998, 999999])

In [9]:
my_list=list(range(1000000))

In [10]:
%time for _ in range(10):my_arr2=my_arr*2

Wall time: 21.5 ms


In [12]:
%time for _ in range(10):my_list2=[x*2 for x in my_list]

Wall time: 690 ms


#### 2 ndarray：一种多维数组对象

大数据集容器，利用这种数组对整块数执行一些数学运算，其语法跟标量元素之间的运算一样。

In [14]:
import numpy as np

In [15]:
data=np.random.randn(2,3)

In [16]:
data

array([[ 1.40489178,  1.46769014, -0.17741143],
       [-0.00275477, -1.02202838,  0.39663208]])

In [17]:
data*10

array([[ 14.04891784,  14.67690144,  -1.77411428],
       [ -0.02754771, -10.22028384,   3.96632084]])

In [18]:
data+data

array([[ 2.80978357,  2.93538029, -0.35482286],
       [-0.00550954, -2.04405677,  0.79326417]])

**Note**:
ndarray是一个通用的同构数据多维容器，其中的所有元素必须是相同类型的。
       
       每个数组都有一个shape（一个表示各维度大小的元组）
       和一个dtype（一个用于说明数组数据类型的对象）。

In [19]:
data.shape

(2, 3)

In [20]:
data.dtype

dtype('float64')

#### 3 创建ndarray

使用array函数，它接受一切序列型的对象（包括其他数组），然后产生一个新的含有传入数据的NumPy数组。

In [21]:
data1=[6,6.75,3,8,2]

In [22]:
arr1=np.array(data1)

In [23]:
arr1

array([6.  , 6.75, 3.  , 8.  , 2.  ])

嵌套序列---->多维数组：

In [24]:
data2=[[1,2,3,4],[5,6,7,8]]

In [25]:
arr2=np.array(data2)

In [26]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [27]:
arr2.ndim

2

In [28]:
arr2.shape

(2, 4)

In [31]:
arr2.dtype

dtype('int32')

In [30]:
arr1.dtype

dtype('float64')

In [32]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [33]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [34]:
np.empty((2,3,2))

array([[[0.00000000e+000, 6.36598737e-314],
        [0.00000000e+000, 1.27319747e-313],
        [1.27319747e-313, 1.27319747e-313]],

       [[1.27319747e-313, 1.27319747e-313],
        [0.00000000e+000, 4.44659081e-323],
        [2.54639495e-313, 6.42285340e-323]]])

In [35]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

使用astype方法转换数组的dtype：

In [36]:
arr=np.array([1,2,3,4,5])

In [42]:
arr

array([1, 2, 3, 4, 5])

In [38]:
arr.dtype

dtype('int32')

In [39]:
float_arr=arr.astype(np.float64)

In [40]:
float_arr.dtype

dtype('float64')

In [41]:
float_arr

array([1., 2., 3., 4., 5.])

如果某字符串数组表示的全是数字，也可以用astype将其转换成数值形式。

不同大小的数组之间的运算叫做广播。